"""stored files

Revision ID: 5605446c55ff
Revises: c1f59d788b9a
Create Date: 2026-09-23 20:08:10.650985
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5605446c55ff"
down_revision: str | None = "c1f59d788b9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stored_files",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_stored_files")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stored_files")
    # ### end Alembic commands ###
